### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by lidense** [AndrewLighten/fit-peaks#1]
Hi there, when I run python3 fitpeaks power  I get an error message:
"Cannot load athlete data (ftp, HR, etc). Cannot proceed."
This seems to be due to the fact that there is no "/.athlete.json.
What should there be in that file? Do you have an example of how to fill it in?
Thanks
Dave

**Comment by AndrewLighten** [comment]
Dang — I should have documented that. Sorry!

It's a list of dates, and the FTP, resting heart rate, threshold heart rate, and maximum heart rate that apply from that date onward.

Here's my current file:

```
[
    {"date":"01-Jan-1990", "ftp":279, "rhr":42, "thr": 155, "mhr": 184},
    {"date":"10-Dec-2019", "ftp":316, "rhr":41, "thr": 155, "mhr": 184},
    {"date":"23-Dec-2019", "ftp":322, "rhr":41, "thr": 155, "mhr": 184},
    {"date":"31-Dec-2019", "ftp":335, "rhr":41, "thr": 156, "mhr": 184},
    {"date":"18-Feb-2020", "ftp":338, "rhr":40, "thr": 156, "mhr": 184},
    {"date":"25-Feb-2020", "ftp":341, "rhr":40, "thr": 156, "mhr": 184},
    {"date":"28-Feb-2020", "ftp":354, "rhr":39, "thr": 156, "mhr": 184},
    {"date":"19-Jul-2020", "ftp":319, "rhr":42, "thr": 158, "mhr": 175}
]
```

_(Yes, my FTP plummeted when I went from a wheel-on trainer with power meter to a Kickr. And yes, I really should do another FTP test since the last one was nearly 6 months ago.)_

**Comment by lidense** [comment]
OK thanks, looks great and useful, good job! I'm going through the code to try and understand how it works.
I'm discovering zwift, I'm using HR2VP for power and I am interested in python coding!
Regards
David


----- Mail original -----
De: "AndrewLighten" <notifications@github.com>
À: "AndrewLighten/fit-peaks" <fit-peaks@noreply.github.com>
Cc: "lidense" <d.radzik@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 16 Février 2021 23:42:57
Objet: Re: [AndrewLighten/fit-peaks] Problem (#1)





Dang — I should have documented that. Sorry! 

It's a list of dates, and the FTP, resting heart rate, threshold heart rate, and maximum heart rate that apply from that date onward. 

Here's my current file: [

    {"date":"01-Jan-1990", "ftp":279, "rhr":42, "thr": 155, "mhr": 184},

    {"date":"10-Dec-2019", "ftp":316, "rhr":41, "thr": 155, "mhr": 184},

    {"date":"23-Dec-2019", "ftp":322, "rhr":41, "thr": 155, "mhr": 184},

    {"date":"31-Dec-2019", "ftp":335, "rhr":41, "thr": 156, "mhr": 184},

    {"date":"18-Feb-2020", "ftp":338, "rhr":40, "thr": 156, "mhr": 184},

    {"date":"25-Feb-2020", "ftp":341, "rhr":40, "thr": 156, "mhr": 184},

    {"date":"28-Feb-2020", "ftp":354, "rhr":39, "thr": 156, "mhr": 184},

    {"date":"19-Jul-2020", "ftp":319, "rhr":42, "thr": 158, "mhr": 175}

] 

(Yes, my FTP plummeted when I went from a wheel-on trainer with power meter to a Kickr. And yes, I really should do another FTP test since the last one was nearly 6 months ago.)

**Comment by AndrewLighten** [comment]
Closed
